
# consumer_key=ck_e1c2f9609a4e4c5f4ea86dc821fb638869ff784c
# consumer_secret=cs_a0b743123b8054fc7efb92adcb37a5efbeab6a81

# base64 encoded key Y2tfZTFjMmY5NjA5YTRlNGM1ZjRlYTg2ZGM4MjFmYjYzODg2OWZmNzg0Yzpjc19hMGI3NDMxMjNiODA1NGZjN2VmYjkyYWRjYjM3YTVlZmJlYWI2YTgx

### Get all products

GET https://localhost/wp-json/wc/v3/products
Content-Type: application/json
Authorization: Basic Y2tfZTFjMmY5NjA5YTRlNGM1ZjRlYTg2ZGM4MjFmYjYzODg2OWZmNzg0Yzpjc19hMGI3NDMxMjNiODA1NGZjN2VmYjkyYWRjYjM3YTVlZmJlYWI2YTgx

### Order a product

POST /wp-json/wc/v3/orders
Content-Type: application/json
Authorization: Basic Y2tfZTFjMmY5NjA5YTRlNGM1ZjRlYTg2ZGM4MjFmYjYzODg2OWZmNzg0Yzpjc19hMGI3NDMxMjNiODA1NGZjN2VmYjkyYWRjYjM3YTVlZmJlYWI2YTgx

{
  "line_items": [
    { "product_id": 26, "quantity": 1 }
  ]
}

### Update order

PUT /wp-json/wc/v3/orders/33
Content-Type: application/json
Authorization: Basic Y2tfZTFjMmY5NjA5YTRlNGM1ZjRlYTg2ZGM4MjFmYjYzODg2OWZmNzg0Yzpjc19hMGI3NDMxMjNiODA1NGZjN2VmYjkyYWRjYjM3YTVlZmJlYWI2YTgx

{
  "line_items": [
    { "product_id": 26, "quantity": 2 }
  ]
}

### Get single product

GET https://localhost/wp-json/wc/v3/products/26
Content-Type: application/json
Authorization: Basic Y2tfZTFjMmY5NjA5YTRlNGM1ZjRlYTg2ZGM4MjFmYjYzODg2OWZmNzg0Yzpjc19hMGI3NDMxMjNiODA1NGZjN2VmYjkyYWRjYjM3YTVlZmJlYWI2YTgx

### Add product to order

POST https://localhost/wp-json/wc/v3/orders
Content-Type: application/json
Authorization: Basic Y2tfZTFjMmY5NjA5YTRlNGM1ZjRlYTg2ZGM4MjFmYjYzODg2OWZmNzg0Yzpjc19hMGI3NDMxMjNiODA1NGZjN2VmYjkyYWRjYjM3YTVlZmJlYWI2YTgx

{
  "line_items": [
    { "product_id": 26, "quantity": 1 }
  ]
}

### Get orders 
# Cart does not exist in WooCommerce REST API, so we use orders instead. 
# Orders are sensitive, so WooCommerce requires a valid consumer key/secret with permissions.

GET https://localhost/wp-json/wc/v3/orders
Content-Type: application/json
Authorization: Basic Y2tfZTFjMmY5NjA5YTRlNGM1ZjRlYTg2ZGM4MjFmYjYzODg2OWZmNzg0Yzpjc19hMGI3NDMxMjNiODA1NGZjN2VmYjkyYWRjYjM3YTVlZmJlYWI2YTgx
